// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientInfo.proto

package com.temas.aimaster;

public final class ClientInfoOuterClass {
  private ClientInfoOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ActionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.temas.aimaster.Action)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .com.temas.aimaster.Vector2 startPoint = 1;</code>
     */
    boolean hasStartPoint();
    /**
     * <code>optional .com.temas.aimaster.Vector2 startPoint = 1;</code>
     */
    com.temas.aimaster.Common.Vector2 getStartPoint();
    /**
     * <code>optional .com.temas.aimaster.Vector2 startPoint = 1;</code>
     */
    com.temas.aimaster.Common.Vector2OrBuilder getStartPointOrBuilder();

    /**
     * <code>optional .com.temas.aimaster.Vector2 direction = 2;</code>
     */
    boolean hasDirection();
    /**
     * <code>optional .com.temas.aimaster.Vector2 direction = 2;</code>
     */
    com.temas.aimaster.Common.Vector2 getDirection();
    /**
     * <code>optional .com.temas.aimaster.Vector2 direction = 2;</code>
     */
    com.temas.aimaster.Common.Vector2OrBuilder getDirectionOrBuilder();

    /**
     * <code>optional float speed = 3;</code>
     */
    float getSpeed();
  }
  /**
   * Protobuf type {@code com.temas.aimaster.Action}
   */
  public  static final class Action extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.temas.aimaster.Action)
      ActionOrBuilder {
    // Use Action.newBuilder() to construct.
    private Action(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private Action() {
      speed_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Action(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.temas.aimaster.Common.Vector2.Builder subBuilder = null;
              if (startPoint_ != null) {
                subBuilder = startPoint_.toBuilder();
              }
              startPoint_ = input.readMessage(com.temas.aimaster.Common.Vector2.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(startPoint_);
                startPoint_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              com.temas.aimaster.Common.Vector2.Builder subBuilder = null;
              if (direction_ != null) {
                subBuilder = direction_.toBuilder();
              }
              direction_ = input.readMessage(com.temas.aimaster.Common.Vector2.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(direction_);
                direction_ = subBuilder.buildPartial();
              }

              break;
            }
            case 29: {

              speed_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.temas.aimaster.ClientInfoOuterClass.internal_static_com_temas_aimaster_Action_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.temas.aimaster.ClientInfoOuterClass.internal_static_com_temas_aimaster_Action_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.temas.aimaster.ClientInfoOuterClass.Action.class, com.temas.aimaster.ClientInfoOuterClass.Action.Builder.class);
    }

    public static final int STARTPOINT_FIELD_NUMBER = 1;
    private com.temas.aimaster.Common.Vector2 startPoint_;
    /**
     * <code>optional .com.temas.aimaster.Vector2 startPoint = 1;</code>
     */
    public boolean hasStartPoint() {
      return startPoint_ != null;
    }
    /**
     * <code>optional .com.temas.aimaster.Vector2 startPoint = 1;</code>
     */
    public com.temas.aimaster.Common.Vector2 getStartPoint() {
      return startPoint_ == null ? com.temas.aimaster.Common.Vector2.getDefaultInstance() : startPoint_;
    }
    /**
     * <code>optional .com.temas.aimaster.Vector2 startPoint = 1;</code>
     */
    public com.temas.aimaster.Common.Vector2OrBuilder getStartPointOrBuilder() {
      return getStartPoint();
    }

    public static final int DIRECTION_FIELD_NUMBER = 2;
    private com.temas.aimaster.Common.Vector2 direction_;
    /**
     * <code>optional .com.temas.aimaster.Vector2 direction = 2;</code>
     */
    public boolean hasDirection() {
      return direction_ != null;
    }
    /**
     * <code>optional .com.temas.aimaster.Vector2 direction = 2;</code>
     */
    public com.temas.aimaster.Common.Vector2 getDirection() {
      return direction_ == null ? com.temas.aimaster.Common.Vector2.getDefaultInstance() : direction_;
    }
    /**
     * <code>optional .com.temas.aimaster.Vector2 direction = 2;</code>
     */
    public com.temas.aimaster.Common.Vector2OrBuilder getDirectionOrBuilder() {
      return getDirection();
    }

    public static final int SPEED_FIELD_NUMBER = 3;
    private float speed_;
    /**
     * <code>optional float speed = 3;</code>
     */
    public float getSpeed() {
      return speed_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (startPoint_ != null) {
        output.writeMessage(1, getStartPoint());
      }
      if (direction_ != null) {
        output.writeMessage(2, getDirection());
      }
      if (speed_ != 0F) {
        output.writeFloat(3, speed_);
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (startPoint_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getStartPoint());
      }
      if (direction_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getDirection());
      }
      if (speed_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, speed_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.temas.aimaster.ClientInfoOuterClass.Action parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.temas.aimaster.ClientInfoOuterClass.Action parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.temas.aimaster.ClientInfoOuterClass.Action parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.temas.aimaster.ClientInfoOuterClass.Action parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.temas.aimaster.ClientInfoOuterClass.Action parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.temas.aimaster.ClientInfoOuterClass.Action parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.temas.aimaster.ClientInfoOuterClass.Action parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.temas.aimaster.ClientInfoOuterClass.Action parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.temas.aimaster.ClientInfoOuterClass.Action parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.temas.aimaster.ClientInfoOuterClass.Action parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.temas.aimaster.ClientInfoOuterClass.Action prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.temas.aimaster.Action}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.temas.aimaster.Action)
        com.temas.aimaster.ClientInfoOuterClass.ActionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.temas.aimaster.ClientInfoOuterClass.internal_static_com_temas_aimaster_Action_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.temas.aimaster.ClientInfoOuterClass.internal_static_com_temas_aimaster_Action_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.temas.aimaster.ClientInfoOuterClass.Action.class, com.temas.aimaster.ClientInfoOuterClass.Action.Builder.class);
      }

      // Construct using com.temas.aimaster.ClientInfoOuterClass.Action.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (startPointBuilder_ == null) {
          startPoint_ = null;
        } else {
          startPoint_ = null;
          startPointBuilder_ = null;
        }
        if (directionBuilder_ == null) {
          direction_ = null;
        } else {
          direction_ = null;
          directionBuilder_ = null;
        }
        speed_ = 0F;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.temas.aimaster.ClientInfoOuterClass.internal_static_com_temas_aimaster_Action_descriptor;
      }

      public com.temas.aimaster.ClientInfoOuterClass.Action getDefaultInstanceForType() {
        return com.temas.aimaster.ClientInfoOuterClass.Action.getDefaultInstance();
      }

      public com.temas.aimaster.ClientInfoOuterClass.Action build() {
        com.temas.aimaster.ClientInfoOuterClass.Action result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.temas.aimaster.ClientInfoOuterClass.Action buildPartial() {
        com.temas.aimaster.ClientInfoOuterClass.Action result = new com.temas.aimaster.ClientInfoOuterClass.Action(this);
        if (startPointBuilder_ == null) {
          result.startPoint_ = startPoint_;
        } else {
          result.startPoint_ = startPointBuilder_.build();
        }
        if (directionBuilder_ == null) {
          result.direction_ = direction_;
        } else {
          result.direction_ = directionBuilder_.build();
        }
        result.speed_ = speed_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.temas.aimaster.ClientInfoOuterClass.Action) {
          return mergeFrom((com.temas.aimaster.ClientInfoOuterClass.Action)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.temas.aimaster.ClientInfoOuterClass.Action other) {
        if (other == com.temas.aimaster.ClientInfoOuterClass.Action.getDefaultInstance()) return this;
        if (other.hasStartPoint()) {
          mergeStartPoint(other.getStartPoint());
        }
        if (other.hasDirection()) {
          mergeDirection(other.getDirection());
        }
        if (other.getSpeed() != 0F) {
          setSpeed(other.getSpeed());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.temas.aimaster.ClientInfoOuterClass.Action parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.temas.aimaster.ClientInfoOuterClass.Action) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.temas.aimaster.Common.Vector2 startPoint_ = null;
      private com.google.protobuf.SingleFieldBuilder<
          com.temas.aimaster.Common.Vector2, com.temas.aimaster.Common.Vector2.Builder, com.temas.aimaster.Common.Vector2OrBuilder> startPointBuilder_;
      /**
       * <code>optional .com.temas.aimaster.Vector2 startPoint = 1;</code>
       */
      public boolean hasStartPoint() {
        return startPointBuilder_ != null || startPoint_ != null;
      }
      /**
       * <code>optional .com.temas.aimaster.Vector2 startPoint = 1;</code>
       */
      public com.temas.aimaster.Common.Vector2 getStartPoint() {
        if (startPointBuilder_ == null) {
          return startPoint_ == null ? com.temas.aimaster.Common.Vector2.getDefaultInstance() : startPoint_;
        } else {
          return startPointBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.temas.aimaster.Vector2 startPoint = 1;</code>
       */
      public Builder setStartPoint(com.temas.aimaster.Common.Vector2 value) {
        if (startPointBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          startPoint_ = value;
          onChanged();
        } else {
          startPointBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .com.temas.aimaster.Vector2 startPoint = 1;</code>
       */
      public Builder setStartPoint(
          com.temas.aimaster.Common.Vector2.Builder builderForValue) {
        if (startPointBuilder_ == null) {
          startPoint_ = builderForValue.build();
          onChanged();
        } else {
          startPointBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .com.temas.aimaster.Vector2 startPoint = 1;</code>
       */
      public Builder mergeStartPoint(com.temas.aimaster.Common.Vector2 value) {
        if (startPointBuilder_ == null) {
          if (startPoint_ != null) {
            startPoint_ =
              com.temas.aimaster.Common.Vector2.newBuilder(startPoint_).mergeFrom(value).buildPartial();
          } else {
            startPoint_ = value;
          }
          onChanged();
        } else {
          startPointBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .com.temas.aimaster.Vector2 startPoint = 1;</code>
       */
      public Builder clearStartPoint() {
        if (startPointBuilder_ == null) {
          startPoint_ = null;
          onChanged();
        } else {
          startPoint_ = null;
          startPointBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .com.temas.aimaster.Vector2 startPoint = 1;</code>
       */
      public com.temas.aimaster.Common.Vector2.Builder getStartPointBuilder() {
        
        onChanged();
        return getStartPointFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.temas.aimaster.Vector2 startPoint = 1;</code>
       */
      public com.temas.aimaster.Common.Vector2OrBuilder getStartPointOrBuilder() {
        if (startPointBuilder_ != null) {
          return startPointBuilder_.getMessageOrBuilder();
        } else {
          return startPoint_ == null ?
              com.temas.aimaster.Common.Vector2.getDefaultInstance() : startPoint_;
        }
      }
      /**
       * <code>optional .com.temas.aimaster.Vector2 startPoint = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.temas.aimaster.Common.Vector2, com.temas.aimaster.Common.Vector2.Builder, com.temas.aimaster.Common.Vector2OrBuilder> 
          getStartPointFieldBuilder() {
        if (startPointBuilder_ == null) {
          startPointBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.temas.aimaster.Common.Vector2, com.temas.aimaster.Common.Vector2.Builder, com.temas.aimaster.Common.Vector2OrBuilder>(
                  getStartPoint(),
                  getParentForChildren(),
                  isClean());
          startPoint_ = null;
        }
        return startPointBuilder_;
      }

      private com.temas.aimaster.Common.Vector2 direction_ = null;
      private com.google.protobuf.SingleFieldBuilder<
          com.temas.aimaster.Common.Vector2, com.temas.aimaster.Common.Vector2.Builder, com.temas.aimaster.Common.Vector2OrBuilder> directionBuilder_;
      /**
       * <code>optional .com.temas.aimaster.Vector2 direction = 2;</code>
       */
      public boolean hasDirection() {
        return directionBuilder_ != null || direction_ != null;
      }
      /**
       * <code>optional .com.temas.aimaster.Vector2 direction = 2;</code>
       */
      public com.temas.aimaster.Common.Vector2 getDirection() {
        if (directionBuilder_ == null) {
          return direction_ == null ? com.temas.aimaster.Common.Vector2.getDefaultInstance() : direction_;
        } else {
          return directionBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.temas.aimaster.Vector2 direction = 2;</code>
       */
      public Builder setDirection(com.temas.aimaster.Common.Vector2 value) {
        if (directionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          direction_ = value;
          onChanged();
        } else {
          directionBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .com.temas.aimaster.Vector2 direction = 2;</code>
       */
      public Builder setDirection(
          com.temas.aimaster.Common.Vector2.Builder builderForValue) {
        if (directionBuilder_ == null) {
          direction_ = builderForValue.build();
          onChanged();
        } else {
          directionBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .com.temas.aimaster.Vector2 direction = 2;</code>
       */
      public Builder mergeDirection(com.temas.aimaster.Common.Vector2 value) {
        if (directionBuilder_ == null) {
          if (direction_ != null) {
            direction_ =
              com.temas.aimaster.Common.Vector2.newBuilder(direction_).mergeFrom(value).buildPartial();
          } else {
            direction_ = value;
          }
          onChanged();
        } else {
          directionBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .com.temas.aimaster.Vector2 direction = 2;</code>
       */
      public Builder clearDirection() {
        if (directionBuilder_ == null) {
          direction_ = null;
          onChanged();
        } else {
          direction_ = null;
          directionBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .com.temas.aimaster.Vector2 direction = 2;</code>
       */
      public com.temas.aimaster.Common.Vector2.Builder getDirectionBuilder() {
        
        onChanged();
        return getDirectionFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.temas.aimaster.Vector2 direction = 2;</code>
       */
      public com.temas.aimaster.Common.Vector2OrBuilder getDirectionOrBuilder() {
        if (directionBuilder_ != null) {
          return directionBuilder_.getMessageOrBuilder();
        } else {
          return direction_ == null ?
              com.temas.aimaster.Common.Vector2.getDefaultInstance() : direction_;
        }
      }
      /**
       * <code>optional .com.temas.aimaster.Vector2 direction = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.temas.aimaster.Common.Vector2, com.temas.aimaster.Common.Vector2.Builder, com.temas.aimaster.Common.Vector2OrBuilder> 
          getDirectionFieldBuilder() {
        if (directionBuilder_ == null) {
          directionBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.temas.aimaster.Common.Vector2, com.temas.aimaster.Common.Vector2.Builder, com.temas.aimaster.Common.Vector2OrBuilder>(
                  getDirection(),
                  getParentForChildren(),
                  isClean());
          direction_ = null;
        }
        return directionBuilder_;
      }

      private float speed_ ;
      /**
       * <code>optional float speed = 3;</code>
       */
      public float getSpeed() {
        return speed_;
      }
      /**
       * <code>optional float speed = 3;</code>
       */
      public Builder setSpeed(float value) {
        
        speed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float speed = 3;</code>
       */
      public Builder clearSpeed() {
        
        speed_ = 0F;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.temas.aimaster.Action)
    }

    // @@protoc_insertion_point(class_scope:com.temas.aimaster.Action)
    private static final com.temas.aimaster.ClientInfoOuterClass.Action DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.temas.aimaster.ClientInfoOuterClass.Action();
    }

    public static com.temas.aimaster.ClientInfoOuterClass.Action getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static final com.google.protobuf.Parser<Action> PARSER =
        new com.google.protobuf.AbstractParser<Action>() {
      public Action parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new Action(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Action> getParserForType() {
      return PARSER;
    }

    public com.temas.aimaster.ClientInfoOuterClass.Action getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ClientInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.temas.aimaster.ClientInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 timestamp = 1;</code>
     */
    long getTimestamp();

    /**
     * <code>optional .com.temas.aimaster.Action action = 2;</code>
     */
    boolean hasAction();
    /**
     * <code>optional .com.temas.aimaster.Action action = 2;</code>
     */
    com.temas.aimaster.ClientInfoOuterClass.Action getAction();
    /**
     * <code>optional .com.temas.aimaster.Action action = 2;</code>
     */
    com.temas.aimaster.ClientInfoOuterClass.ActionOrBuilder getActionOrBuilder();
  }
  /**
   * Protobuf type {@code com.temas.aimaster.ClientInfo}
   */
  public  static final class ClientInfo extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.temas.aimaster.ClientInfo)
      ClientInfoOrBuilder {
    // Use ClientInfo.newBuilder() to construct.
    private ClientInfo(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private ClientInfo() {
      timestamp_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ClientInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              timestamp_ = input.readInt64();
              break;
            }
            case 18: {
              com.temas.aimaster.ClientInfoOuterClass.Action.Builder subBuilder = null;
              if (action_ != null) {
                subBuilder = action_.toBuilder();
              }
              action_ = input.readMessage(com.temas.aimaster.ClientInfoOuterClass.Action.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(action_);
                action_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.temas.aimaster.ClientInfoOuterClass.internal_static_com_temas_aimaster_ClientInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.temas.aimaster.ClientInfoOuterClass.internal_static_com_temas_aimaster_ClientInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.temas.aimaster.ClientInfoOuterClass.ClientInfo.class, com.temas.aimaster.ClientInfoOuterClass.ClientInfo.Builder.class);
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private long timestamp_;
    /**
     * <code>optional int64 timestamp = 1;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int ACTION_FIELD_NUMBER = 2;
    private com.temas.aimaster.ClientInfoOuterClass.Action action_;
    /**
     * <code>optional .com.temas.aimaster.Action action = 2;</code>
     */
    public boolean hasAction() {
      return action_ != null;
    }
    /**
     * <code>optional .com.temas.aimaster.Action action = 2;</code>
     */
    public com.temas.aimaster.ClientInfoOuterClass.Action getAction() {
      return action_ == null ? com.temas.aimaster.ClientInfoOuterClass.Action.getDefaultInstance() : action_;
    }
    /**
     * <code>optional .com.temas.aimaster.Action action = 2;</code>
     */
    public com.temas.aimaster.ClientInfoOuterClass.ActionOrBuilder getActionOrBuilder() {
      return getAction();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (timestamp_ != 0L) {
        output.writeInt64(1, timestamp_);
      }
      if (action_ != null) {
        output.writeMessage(2, getAction());
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, timestamp_);
      }
      if (action_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getAction());
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.temas.aimaster.ClientInfoOuterClass.ClientInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.temas.aimaster.ClientInfoOuterClass.ClientInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.temas.aimaster.ClientInfoOuterClass.ClientInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.temas.aimaster.ClientInfoOuterClass.ClientInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.temas.aimaster.ClientInfoOuterClass.ClientInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.temas.aimaster.ClientInfoOuterClass.ClientInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.temas.aimaster.ClientInfoOuterClass.ClientInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.temas.aimaster.ClientInfoOuterClass.ClientInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.temas.aimaster.ClientInfoOuterClass.ClientInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.temas.aimaster.ClientInfoOuterClass.ClientInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.temas.aimaster.ClientInfoOuterClass.ClientInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.temas.aimaster.ClientInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.temas.aimaster.ClientInfo)
        com.temas.aimaster.ClientInfoOuterClass.ClientInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.temas.aimaster.ClientInfoOuterClass.internal_static_com_temas_aimaster_ClientInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.temas.aimaster.ClientInfoOuterClass.internal_static_com_temas_aimaster_ClientInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.temas.aimaster.ClientInfoOuterClass.ClientInfo.class, com.temas.aimaster.ClientInfoOuterClass.ClientInfo.Builder.class);
      }

      // Construct using com.temas.aimaster.ClientInfoOuterClass.ClientInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        timestamp_ = 0L;

        if (actionBuilder_ == null) {
          action_ = null;
        } else {
          action_ = null;
          actionBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.temas.aimaster.ClientInfoOuterClass.internal_static_com_temas_aimaster_ClientInfo_descriptor;
      }

      public com.temas.aimaster.ClientInfoOuterClass.ClientInfo getDefaultInstanceForType() {
        return com.temas.aimaster.ClientInfoOuterClass.ClientInfo.getDefaultInstance();
      }

      public com.temas.aimaster.ClientInfoOuterClass.ClientInfo build() {
        com.temas.aimaster.ClientInfoOuterClass.ClientInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.temas.aimaster.ClientInfoOuterClass.ClientInfo buildPartial() {
        com.temas.aimaster.ClientInfoOuterClass.ClientInfo result = new com.temas.aimaster.ClientInfoOuterClass.ClientInfo(this);
        result.timestamp_ = timestamp_;
        if (actionBuilder_ == null) {
          result.action_ = action_;
        } else {
          result.action_ = actionBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.temas.aimaster.ClientInfoOuterClass.ClientInfo) {
          return mergeFrom((com.temas.aimaster.ClientInfoOuterClass.ClientInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.temas.aimaster.ClientInfoOuterClass.ClientInfo other) {
        if (other == com.temas.aimaster.ClientInfoOuterClass.ClientInfo.getDefaultInstance()) return this;
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasAction()) {
          mergeAction(other.getAction());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.temas.aimaster.ClientInfoOuterClass.ClientInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.temas.aimaster.ClientInfoOuterClass.ClientInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>optional int64 timestamp = 1;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>optional int64 timestamp = 1;</code>
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 timestamp = 1;</code>
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private com.temas.aimaster.ClientInfoOuterClass.Action action_ = null;
      private com.google.protobuf.SingleFieldBuilder<
          com.temas.aimaster.ClientInfoOuterClass.Action, com.temas.aimaster.ClientInfoOuterClass.Action.Builder, com.temas.aimaster.ClientInfoOuterClass.ActionOrBuilder> actionBuilder_;
      /**
       * <code>optional .com.temas.aimaster.Action action = 2;</code>
       */
      public boolean hasAction() {
        return actionBuilder_ != null || action_ != null;
      }
      /**
       * <code>optional .com.temas.aimaster.Action action = 2;</code>
       */
      public com.temas.aimaster.ClientInfoOuterClass.Action getAction() {
        if (actionBuilder_ == null) {
          return action_ == null ? com.temas.aimaster.ClientInfoOuterClass.Action.getDefaultInstance() : action_;
        } else {
          return actionBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.temas.aimaster.Action action = 2;</code>
       */
      public Builder setAction(com.temas.aimaster.ClientInfoOuterClass.Action value) {
        if (actionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          action_ = value;
          onChanged();
        } else {
          actionBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .com.temas.aimaster.Action action = 2;</code>
       */
      public Builder setAction(
          com.temas.aimaster.ClientInfoOuterClass.Action.Builder builderForValue) {
        if (actionBuilder_ == null) {
          action_ = builderForValue.build();
          onChanged();
        } else {
          actionBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .com.temas.aimaster.Action action = 2;</code>
       */
      public Builder mergeAction(com.temas.aimaster.ClientInfoOuterClass.Action value) {
        if (actionBuilder_ == null) {
          if (action_ != null) {
            action_ =
              com.temas.aimaster.ClientInfoOuterClass.Action.newBuilder(action_).mergeFrom(value).buildPartial();
          } else {
            action_ = value;
          }
          onChanged();
        } else {
          actionBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .com.temas.aimaster.Action action = 2;</code>
       */
      public Builder clearAction() {
        if (actionBuilder_ == null) {
          action_ = null;
          onChanged();
        } else {
          action_ = null;
          actionBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .com.temas.aimaster.Action action = 2;</code>
       */
      public com.temas.aimaster.ClientInfoOuterClass.Action.Builder getActionBuilder() {
        
        onChanged();
        return getActionFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.temas.aimaster.Action action = 2;</code>
       */
      public com.temas.aimaster.ClientInfoOuterClass.ActionOrBuilder getActionOrBuilder() {
        if (actionBuilder_ != null) {
          return actionBuilder_.getMessageOrBuilder();
        } else {
          return action_ == null ?
              com.temas.aimaster.ClientInfoOuterClass.Action.getDefaultInstance() : action_;
        }
      }
      /**
       * <code>optional .com.temas.aimaster.Action action = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.temas.aimaster.ClientInfoOuterClass.Action, com.temas.aimaster.ClientInfoOuterClass.Action.Builder, com.temas.aimaster.ClientInfoOuterClass.ActionOrBuilder> 
          getActionFieldBuilder() {
        if (actionBuilder_ == null) {
          actionBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.temas.aimaster.ClientInfoOuterClass.Action, com.temas.aimaster.ClientInfoOuterClass.Action.Builder, com.temas.aimaster.ClientInfoOuterClass.ActionOrBuilder>(
                  getAction(),
                  getParentForChildren(),
                  isClean());
          action_ = null;
        }
        return actionBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.temas.aimaster.ClientInfo)
    }

    // @@protoc_insertion_point(class_scope:com.temas.aimaster.ClientInfo)
    private static final com.temas.aimaster.ClientInfoOuterClass.ClientInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.temas.aimaster.ClientInfoOuterClass.ClientInfo();
    }

    public static com.temas.aimaster.ClientInfoOuterClass.ClientInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static final com.google.protobuf.Parser<ClientInfo> PARSER =
        new com.google.protobuf.AbstractParser<ClientInfo>() {
      public ClientInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new ClientInfo(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ClientInfo> getParserForType() {
      return PARSER;
    }

    public com.temas.aimaster.ClientInfoOuterClass.ClientInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_temas_aimaster_Action_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_temas_aimaster_Action_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_temas_aimaster_ClientInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_temas_aimaster_ClientInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020ClientInfo.proto\022\022com.temas.aimaster\032\014" +
      "common.proto\"x\n\006Action\022/\n\nstartPoint\030\001 \001" +
      "(\0132\033.com.temas.aimaster.Vector2\022.\n\tdirec" +
      "tion\030\002 \001(\0132\033.com.temas.aimaster.Vector2\022" +
      "\r\n\005speed\030\003 \001(\002\"K\n\nClientInfo\022\021\n\ttimestam" +
      "p\030\001 \001(\003\022*\n\006action\030\002 \001(\0132\032.com.temas.aima" +
      "ster.ActionP\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.temas.aimaster.Common.getDescriptor(),
        }, assigner);
    internal_static_com_temas_aimaster_Action_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_temas_aimaster_Action_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_temas_aimaster_Action_descriptor,
        new java.lang.String[] { "StartPoint", "Direction", "Speed", });
    internal_static_com_temas_aimaster_ClientInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_temas_aimaster_ClientInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_temas_aimaster_ClientInfo_descriptor,
        new java.lang.String[] { "Timestamp", "Action", });
    com.temas.aimaster.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
