// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientProto.proto

package com.temas.aimaster;

public final class ClientProto {
  private ClientProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ThrownStoneOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.temas.aimaster.ThrownStone)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>.com.temas.aimaster.Vector2 startPoint = 2;</code>
     */
    boolean hasStartPoint();
    /**
     * <code>.com.temas.aimaster.Vector2 startPoint = 2;</code>
     */
    com.temas.aimaster.Common.Vector2 getStartPoint();
    /**
     * <code>.com.temas.aimaster.Vector2 startPoint = 2;</code>
     */
    com.temas.aimaster.Common.Vector2OrBuilder getStartPointOrBuilder();

    /**
     * <code>.com.temas.aimaster.Vector2 velocity = 3;</code>
     */
    boolean hasVelocity();
    /**
     * <code>.com.temas.aimaster.Vector2 velocity = 3;</code>
     */
    com.temas.aimaster.Common.Vector2 getVelocity();
    /**
     * <code>.com.temas.aimaster.Vector2 velocity = 3;</code>
     */
    com.temas.aimaster.Common.Vector2OrBuilder getVelocityOrBuilder();
  }
  /**
   * Protobuf type {@code com.temas.aimaster.ThrownStone}
   */
  public  static final class ThrownStone extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.temas.aimaster.ThrownStone)
      ThrownStoneOrBuilder {
    // Use ThrownStone.newBuilder() to construct.
    private ThrownStone(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ThrownStone() {
      id_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ThrownStone(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              com.temas.aimaster.Common.Vector2.Builder subBuilder = null;
              if (startPoint_ != null) {
                subBuilder = startPoint_.toBuilder();
              }
              startPoint_ = input.readMessage(com.temas.aimaster.Common.Vector2.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(startPoint_);
                startPoint_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              com.temas.aimaster.Common.Vector2.Builder subBuilder = null;
              if (velocity_ != null) {
                subBuilder = velocity_.toBuilder();
              }
              velocity_ = input.readMessage(com.temas.aimaster.Common.Vector2.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(velocity_);
                velocity_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.temas.aimaster.ClientProto.internal_static_com_temas_aimaster_ThrownStone_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.temas.aimaster.ClientProto.internal_static_com_temas_aimaster_ThrownStone_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.temas.aimaster.ClientProto.ThrownStone.class, com.temas.aimaster.ClientProto.ThrownStone.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int STARTPOINT_FIELD_NUMBER = 2;
    private com.temas.aimaster.Common.Vector2 startPoint_;
    /**
     * <code>.com.temas.aimaster.Vector2 startPoint = 2;</code>
     */
    public boolean hasStartPoint() {
      return startPoint_ != null;
    }
    /**
     * <code>.com.temas.aimaster.Vector2 startPoint = 2;</code>
     */
    public com.temas.aimaster.Common.Vector2 getStartPoint() {
      return startPoint_ == null ? com.temas.aimaster.Common.Vector2.getDefaultInstance() : startPoint_;
    }
    /**
     * <code>.com.temas.aimaster.Vector2 startPoint = 2;</code>
     */
    public com.temas.aimaster.Common.Vector2OrBuilder getStartPointOrBuilder() {
      return getStartPoint();
    }

    public static final int VELOCITY_FIELD_NUMBER = 3;
    private com.temas.aimaster.Common.Vector2 velocity_;
    /**
     * <code>.com.temas.aimaster.Vector2 velocity = 3;</code>
     */
    public boolean hasVelocity() {
      return velocity_ != null;
    }
    /**
     * <code>.com.temas.aimaster.Vector2 velocity = 3;</code>
     */
    public com.temas.aimaster.Common.Vector2 getVelocity() {
      return velocity_ == null ? com.temas.aimaster.Common.Vector2.getDefaultInstance() : velocity_;
    }
    /**
     * <code>.com.temas.aimaster.Vector2 velocity = 3;</code>
     */
    public com.temas.aimaster.Common.Vector2OrBuilder getVelocityOrBuilder() {
      return getVelocity();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (startPoint_ != null) {
        output.writeMessage(2, getStartPoint());
      }
      if (velocity_ != null) {
        output.writeMessage(3, getVelocity());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (startPoint_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getStartPoint());
      }
      if (velocity_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getVelocity());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.temas.aimaster.ClientProto.ThrownStone)) {
        return super.equals(obj);
      }
      com.temas.aimaster.ClientProto.ThrownStone other = (com.temas.aimaster.ClientProto.ThrownStone) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && (hasStartPoint() == other.hasStartPoint());
      if (hasStartPoint()) {
        result = result && getStartPoint()
            .equals(other.getStartPoint());
      }
      result = result && (hasVelocity() == other.hasVelocity());
      if (hasVelocity()) {
        result = result && getVelocity()
            .equals(other.getVelocity());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      if (hasStartPoint()) {
        hash = (37 * hash) + STARTPOINT_FIELD_NUMBER;
        hash = (53 * hash) + getStartPoint().hashCode();
      }
      if (hasVelocity()) {
        hash = (37 * hash) + VELOCITY_FIELD_NUMBER;
        hash = (53 * hash) + getVelocity().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.temas.aimaster.ClientProto.ThrownStone parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.temas.aimaster.ClientProto.ThrownStone parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.temas.aimaster.ClientProto.ThrownStone parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.temas.aimaster.ClientProto.ThrownStone parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.temas.aimaster.ClientProto.ThrownStone parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.temas.aimaster.ClientProto.ThrownStone parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.temas.aimaster.ClientProto.ThrownStone parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.temas.aimaster.ClientProto.ThrownStone parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.temas.aimaster.ClientProto.ThrownStone parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.temas.aimaster.ClientProto.ThrownStone parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.temas.aimaster.ClientProto.ThrownStone parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.temas.aimaster.ClientProto.ThrownStone parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.temas.aimaster.ClientProto.ThrownStone prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.temas.aimaster.ThrownStone}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.temas.aimaster.ThrownStone)
        com.temas.aimaster.ClientProto.ThrownStoneOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.temas.aimaster.ClientProto.internal_static_com_temas_aimaster_ThrownStone_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.temas.aimaster.ClientProto.internal_static_com_temas_aimaster_ThrownStone_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.temas.aimaster.ClientProto.ThrownStone.class, com.temas.aimaster.ClientProto.ThrownStone.Builder.class);
      }

      // Construct using com.temas.aimaster.ClientProto.ThrownStone.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;

        if (startPointBuilder_ == null) {
          startPoint_ = null;
        } else {
          startPoint_ = null;
          startPointBuilder_ = null;
        }
        if (velocityBuilder_ == null) {
          velocity_ = null;
        } else {
          velocity_ = null;
          velocityBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.temas.aimaster.ClientProto.internal_static_com_temas_aimaster_ThrownStone_descriptor;
      }

      public com.temas.aimaster.ClientProto.ThrownStone getDefaultInstanceForType() {
        return com.temas.aimaster.ClientProto.ThrownStone.getDefaultInstance();
      }

      public com.temas.aimaster.ClientProto.ThrownStone build() {
        com.temas.aimaster.ClientProto.ThrownStone result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.temas.aimaster.ClientProto.ThrownStone buildPartial() {
        com.temas.aimaster.ClientProto.ThrownStone result = new com.temas.aimaster.ClientProto.ThrownStone(this);
        result.id_ = id_;
        if (startPointBuilder_ == null) {
          result.startPoint_ = startPoint_;
        } else {
          result.startPoint_ = startPointBuilder_.build();
        }
        if (velocityBuilder_ == null) {
          result.velocity_ = velocity_;
        } else {
          result.velocity_ = velocityBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.temas.aimaster.ClientProto.ThrownStone) {
          return mergeFrom((com.temas.aimaster.ClientProto.ThrownStone)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.temas.aimaster.ClientProto.ThrownStone other) {
        if (other == com.temas.aimaster.ClientProto.ThrownStone.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.hasStartPoint()) {
          mergeStartPoint(other.getStartPoint());
        }
        if (other.hasVelocity()) {
          mergeVelocity(other.getVelocity());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.temas.aimaster.ClientProto.ThrownStone parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.temas.aimaster.ClientProto.ThrownStone) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private com.temas.aimaster.Common.Vector2 startPoint_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.temas.aimaster.Common.Vector2, com.temas.aimaster.Common.Vector2.Builder, com.temas.aimaster.Common.Vector2OrBuilder> startPointBuilder_;
      /**
       * <code>.com.temas.aimaster.Vector2 startPoint = 2;</code>
       */
      public boolean hasStartPoint() {
        return startPointBuilder_ != null || startPoint_ != null;
      }
      /**
       * <code>.com.temas.aimaster.Vector2 startPoint = 2;</code>
       */
      public com.temas.aimaster.Common.Vector2 getStartPoint() {
        if (startPointBuilder_ == null) {
          return startPoint_ == null ? com.temas.aimaster.Common.Vector2.getDefaultInstance() : startPoint_;
        } else {
          return startPointBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.temas.aimaster.Vector2 startPoint = 2;</code>
       */
      public Builder setStartPoint(com.temas.aimaster.Common.Vector2 value) {
        if (startPointBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          startPoint_ = value;
          onChanged();
        } else {
          startPointBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.temas.aimaster.Vector2 startPoint = 2;</code>
       */
      public Builder setStartPoint(
          com.temas.aimaster.Common.Vector2.Builder builderForValue) {
        if (startPointBuilder_ == null) {
          startPoint_ = builderForValue.build();
          onChanged();
        } else {
          startPointBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.temas.aimaster.Vector2 startPoint = 2;</code>
       */
      public Builder mergeStartPoint(com.temas.aimaster.Common.Vector2 value) {
        if (startPointBuilder_ == null) {
          if (startPoint_ != null) {
            startPoint_ =
              com.temas.aimaster.Common.Vector2.newBuilder(startPoint_).mergeFrom(value).buildPartial();
          } else {
            startPoint_ = value;
          }
          onChanged();
        } else {
          startPointBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.temas.aimaster.Vector2 startPoint = 2;</code>
       */
      public Builder clearStartPoint() {
        if (startPointBuilder_ == null) {
          startPoint_ = null;
          onChanged();
        } else {
          startPoint_ = null;
          startPointBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.temas.aimaster.Vector2 startPoint = 2;</code>
       */
      public com.temas.aimaster.Common.Vector2.Builder getStartPointBuilder() {
        
        onChanged();
        return getStartPointFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.temas.aimaster.Vector2 startPoint = 2;</code>
       */
      public com.temas.aimaster.Common.Vector2OrBuilder getStartPointOrBuilder() {
        if (startPointBuilder_ != null) {
          return startPointBuilder_.getMessageOrBuilder();
        } else {
          return startPoint_ == null ?
              com.temas.aimaster.Common.Vector2.getDefaultInstance() : startPoint_;
        }
      }
      /**
       * <code>.com.temas.aimaster.Vector2 startPoint = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.temas.aimaster.Common.Vector2, com.temas.aimaster.Common.Vector2.Builder, com.temas.aimaster.Common.Vector2OrBuilder> 
          getStartPointFieldBuilder() {
        if (startPointBuilder_ == null) {
          startPointBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.temas.aimaster.Common.Vector2, com.temas.aimaster.Common.Vector2.Builder, com.temas.aimaster.Common.Vector2OrBuilder>(
                  getStartPoint(),
                  getParentForChildren(),
                  isClean());
          startPoint_ = null;
        }
        return startPointBuilder_;
      }

      private com.temas.aimaster.Common.Vector2 velocity_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.temas.aimaster.Common.Vector2, com.temas.aimaster.Common.Vector2.Builder, com.temas.aimaster.Common.Vector2OrBuilder> velocityBuilder_;
      /**
       * <code>.com.temas.aimaster.Vector2 velocity = 3;</code>
       */
      public boolean hasVelocity() {
        return velocityBuilder_ != null || velocity_ != null;
      }
      /**
       * <code>.com.temas.aimaster.Vector2 velocity = 3;</code>
       */
      public com.temas.aimaster.Common.Vector2 getVelocity() {
        if (velocityBuilder_ == null) {
          return velocity_ == null ? com.temas.aimaster.Common.Vector2.getDefaultInstance() : velocity_;
        } else {
          return velocityBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.temas.aimaster.Vector2 velocity = 3;</code>
       */
      public Builder setVelocity(com.temas.aimaster.Common.Vector2 value) {
        if (velocityBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          velocity_ = value;
          onChanged();
        } else {
          velocityBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.temas.aimaster.Vector2 velocity = 3;</code>
       */
      public Builder setVelocity(
          com.temas.aimaster.Common.Vector2.Builder builderForValue) {
        if (velocityBuilder_ == null) {
          velocity_ = builderForValue.build();
          onChanged();
        } else {
          velocityBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.temas.aimaster.Vector2 velocity = 3;</code>
       */
      public Builder mergeVelocity(com.temas.aimaster.Common.Vector2 value) {
        if (velocityBuilder_ == null) {
          if (velocity_ != null) {
            velocity_ =
              com.temas.aimaster.Common.Vector2.newBuilder(velocity_).mergeFrom(value).buildPartial();
          } else {
            velocity_ = value;
          }
          onChanged();
        } else {
          velocityBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.temas.aimaster.Vector2 velocity = 3;</code>
       */
      public Builder clearVelocity() {
        if (velocityBuilder_ == null) {
          velocity_ = null;
          onChanged();
        } else {
          velocity_ = null;
          velocityBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.temas.aimaster.Vector2 velocity = 3;</code>
       */
      public com.temas.aimaster.Common.Vector2.Builder getVelocityBuilder() {
        
        onChanged();
        return getVelocityFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.temas.aimaster.Vector2 velocity = 3;</code>
       */
      public com.temas.aimaster.Common.Vector2OrBuilder getVelocityOrBuilder() {
        if (velocityBuilder_ != null) {
          return velocityBuilder_.getMessageOrBuilder();
        } else {
          return velocity_ == null ?
              com.temas.aimaster.Common.Vector2.getDefaultInstance() : velocity_;
        }
      }
      /**
       * <code>.com.temas.aimaster.Vector2 velocity = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.temas.aimaster.Common.Vector2, com.temas.aimaster.Common.Vector2.Builder, com.temas.aimaster.Common.Vector2OrBuilder> 
          getVelocityFieldBuilder() {
        if (velocityBuilder_ == null) {
          velocityBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.temas.aimaster.Common.Vector2, com.temas.aimaster.Common.Vector2.Builder, com.temas.aimaster.Common.Vector2OrBuilder>(
                  getVelocity(),
                  getParentForChildren(),
                  isClean());
          velocity_ = null;
        }
        return velocityBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.temas.aimaster.ThrownStone)
    }

    // @@protoc_insertion_point(class_scope:com.temas.aimaster.ThrownStone)
    private static final com.temas.aimaster.ClientProto.ThrownStone DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.temas.aimaster.ClientProto.ThrownStone();
    }

    public static com.temas.aimaster.ClientProto.ThrownStone getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ThrownStone>
        PARSER = new com.google.protobuf.AbstractParser<ThrownStone>() {
      public ThrownStone parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ThrownStone(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ThrownStone> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ThrownStone> getParserForType() {
      return PARSER;
    }

    public com.temas.aimaster.ClientProto.ThrownStone getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ClientDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.temas.aimaster.ClientData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 timeStamp = 1;</code>
     */
    long getTimeStamp();

    /**
     * <pre>
     *not used yet
     * </pre>
     *
     * <code>int64 packId = 2;</code>
     */
    long getPackId();

    /**
     * <code>repeated .com.temas.aimaster.ThrownStone throwActions = 3;</code>
     */
    java.util.List<com.temas.aimaster.ClientProto.ThrownStone> 
        getThrowActionsList();
    /**
     * <code>repeated .com.temas.aimaster.ThrownStone throwActions = 3;</code>
     */
    com.temas.aimaster.ClientProto.ThrownStone getThrowActions(int index);
    /**
     * <code>repeated .com.temas.aimaster.ThrownStone throwActions = 3;</code>
     */
    int getThrowActionsCount();
    /**
     * <code>repeated .com.temas.aimaster.ThrownStone throwActions = 3;</code>
     */
    java.util.List<? extends com.temas.aimaster.ClientProto.ThrownStoneOrBuilder> 
        getThrowActionsOrBuilderList();
    /**
     * <code>repeated .com.temas.aimaster.ThrownStone throwActions = 3;</code>
     */
    com.temas.aimaster.ClientProto.ThrownStoneOrBuilder getThrowActionsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.temas.aimaster.ClientData}
   */
  public  static final class ClientData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.temas.aimaster.ClientData)
      ClientDataOrBuilder {
    // Use ClientData.newBuilder() to construct.
    private ClientData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ClientData() {
      timeStamp_ = 0L;
      packId_ = 0L;
      throwActions_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ClientData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              timeStamp_ = input.readInt64();
              break;
            }
            case 16: {

              packId_ = input.readInt64();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                throwActions_ = new java.util.ArrayList<com.temas.aimaster.ClientProto.ThrownStone>();
                mutable_bitField0_ |= 0x00000004;
              }
              throwActions_.add(
                  input.readMessage(com.temas.aimaster.ClientProto.ThrownStone.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          throwActions_ = java.util.Collections.unmodifiableList(throwActions_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.temas.aimaster.ClientProto.internal_static_com_temas_aimaster_ClientData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.temas.aimaster.ClientProto.internal_static_com_temas_aimaster_ClientData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.temas.aimaster.ClientProto.ClientData.class, com.temas.aimaster.ClientProto.ClientData.Builder.class);
    }

    private int bitField0_;
    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private long timeStamp_;
    /**
     * <code>int64 timeStamp = 1;</code>
     */
    public long getTimeStamp() {
      return timeStamp_;
    }

    public static final int PACKID_FIELD_NUMBER = 2;
    private long packId_;
    /**
     * <pre>
     *not used yet
     * </pre>
     *
     * <code>int64 packId = 2;</code>
     */
    public long getPackId() {
      return packId_;
    }

    public static final int THROWACTIONS_FIELD_NUMBER = 3;
    private java.util.List<com.temas.aimaster.ClientProto.ThrownStone> throwActions_;
    /**
     * <code>repeated .com.temas.aimaster.ThrownStone throwActions = 3;</code>
     */
    public java.util.List<com.temas.aimaster.ClientProto.ThrownStone> getThrowActionsList() {
      return throwActions_;
    }
    /**
     * <code>repeated .com.temas.aimaster.ThrownStone throwActions = 3;</code>
     */
    public java.util.List<? extends com.temas.aimaster.ClientProto.ThrownStoneOrBuilder> 
        getThrowActionsOrBuilderList() {
      return throwActions_;
    }
    /**
     * <code>repeated .com.temas.aimaster.ThrownStone throwActions = 3;</code>
     */
    public int getThrowActionsCount() {
      return throwActions_.size();
    }
    /**
     * <code>repeated .com.temas.aimaster.ThrownStone throwActions = 3;</code>
     */
    public com.temas.aimaster.ClientProto.ThrownStone getThrowActions(int index) {
      return throwActions_.get(index);
    }
    /**
     * <code>repeated .com.temas.aimaster.ThrownStone throwActions = 3;</code>
     */
    public com.temas.aimaster.ClientProto.ThrownStoneOrBuilder getThrowActionsOrBuilder(
        int index) {
      return throwActions_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (timeStamp_ != 0L) {
        output.writeInt64(1, timeStamp_);
      }
      if (packId_ != 0L) {
        output.writeInt64(2, packId_);
      }
      for (int i = 0; i < throwActions_.size(); i++) {
        output.writeMessage(3, throwActions_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (timeStamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, timeStamp_);
      }
      if (packId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, packId_);
      }
      for (int i = 0; i < throwActions_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, throwActions_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.temas.aimaster.ClientProto.ClientData)) {
        return super.equals(obj);
      }
      com.temas.aimaster.ClientProto.ClientData other = (com.temas.aimaster.ClientProto.ClientData) obj;

      boolean result = true;
      result = result && (getTimeStamp()
          == other.getTimeStamp());
      result = result && (getPackId()
          == other.getPackId());
      result = result && getThrowActionsList()
          .equals(other.getThrowActionsList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimeStamp());
      hash = (37 * hash) + PACKID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPackId());
      if (getThrowActionsCount() > 0) {
        hash = (37 * hash) + THROWACTIONS_FIELD_NUMBER;
        hash = (53 * hash) + getThrowActionsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.temas.aimaster.ClientProto.ClientData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.temas.aimaster.ClientProto.ClientData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.temas.aimaster.ClientProto.ClientData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.temas.aimaster.ClientProto.ClientData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.temas.aimaster.ClientProto.ClientData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.temas.aimaster.ClientProto.ClientData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.temas.aimaster.ClientProto.ClientData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.temas.aimaster.ClientProto.ClientData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.temas.aimaster.ClientProto.ClientData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.temas.aimaster.ClientProto.ClientData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.temas.aimaster.ClientProto.ClientData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.temas.aimaster.ClientProto.ClientData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.temas.aimaster.ClientProto.ClientData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.temas.aimaster.ClientData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.temas.aimaster.ClientData)
        com.temas.aimaster.ClientProto.ClientDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.temas.aimaster.ClientProto.internal_static_com_temas_aimaster_ClientData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.temas.aimaster.ClientProto.internal_static_com_temas_aimaster_ClientData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.temas.aimaster.ClientProto.ClientData.class, com.temas.aimaster.ClientProto.ClientData.Builder.class);
      }

      // Construct using com.temas.aimaster.ClientProto.ClientData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getThrowActionsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        timeStamp_ = 0L;

        packId_ = 0L;

        if (throwActionsBuilder_ == null) {
          throwActions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          throwActionsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.temas.aimaster.ClientProto.internal_static_com_temas_aimaster_ClientData_descriptor;
      }

      public com.temas.aimaster.ClientProto.ClientData getDefaultInstanceForType() {
        return com.temas.aimaster.ClientProto.ClientData.getDefaultInstance();
      }

      public com.temas.aimaster.ClientProto.ClientData build() {
        com.temas.aimaster.ClientProto.ClientData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.temas.aimaster.ClientProto.ClientData buildPartial() {
        com.temas.aimaster.ClientProto.ClientData result = new com.temas.aimaster.ClientProto.ClientData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.timeStamp_ = timeStamp_;
        result.packId_ = packId_;
        if (throwActionsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            throwActions_ = java.util.Collections.unmodifiableList(throwActions_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.throwActions_ = throwActions_;
        } else {
          result.throwActions_ = throwActionsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.temas.aimaster.ClientProto.ClientData) {
          return mergeFrom((com.temas.aimaster.ClientProto.ClientData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.temas.aimaster.ClientProto.ClientData other) {
        if (other == com.temas.aimaster.ClientProto.ClientData.getDefaultInstance()) return this;
        if (other.getTimeStamp() != 0L) {
          setTimeStamp(other.getTimeStamp());
        }
        if (other.getPackId() != 0L) {
          setPackId(other.getPackId());
        }
        if (throwActionsBuilder_ == null) {
          if (!other.throwActions_.isEmpty()) {
            if (throwActions_.isEmpty()) {
              throwActions_ = other.throwActions_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureThrowActionsIsMutable();
              throwActions_.addAll(other.throwActions_);
            }
            onChanged();
          }
        } else {
          if (!other.throwActions_.isEmpty()) {
            if (throwActionsBuilder_.isEmpty()) {
              throwActionsBuilder_.dispose();
              throwActionsBuilder_ = null;
              throwActions_ = other.throwActions_;
              bitField0_ = (bitField0_ & ~0x00000004);
              throwActionsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getThrowActionsFieldBuilder() : null;
            } else {
              throwActionsBuilder_.addAllMessages(other.throwActions_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.temas.aimaster.ClientProto.ClientData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.temas.aimaster.ClientProto.ClientData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long timeStamp_ ;
      /**
       * <code>int64 timeStamp = 1;</code>
       */
      public long getTimeStamp() {
        return timeStamp_;
      }
      /**
       * <code>int64 timeStamp = 1;</code>
       */
      public Builder setTimeStamp(long value) {
        
        timeStamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timeStamp = 1;</code>
       */
      public Builder clearTimeStamp() {
        
        timeStamp_ = 0L;
        onChanged();
        return this;
      }

      private long packId_ ;
      /**
       * <pre>
       *not used yet
       * </pre>
       *
       * <code>int64 packId = 2;</code>
       */
      public long getPackId() {
        return packId_;
      }
      /**
       * <pre>
       *not used yet
       * </pre>
       *
       * <code>int64 packId = 2;</code>
       */
      public Builder setPackId(long value) {
        
        packId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *not used yet
       * </pre>
       *
       * <code>int64 packId = 2;</code>
       */
      public Builder clearPackId() {
        
        packId_ = 0L;
        onChanged();
        return this;
      }

      private java.util.List<com.temas.aimaster.ClientProto.ThrownStone> throwActions_ =
        java.util.Collections.emptyList();
      private void ensureThrowActionsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          throwActions_ = new java.util.ArrayList<com.temas.aimaster.ClientProto.ThrownStone>(throwActions_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.temas.aimaster.ClientProto.ThrownStone, com.temas.aimaster.ClientProto.ThrownStone.Builder, com.temas.aimaster.ClientProto.ThrownStoneOrBuilder> throwActionsBuilder_;

      /**
       * <code>repeated .com.temas.aimaster.ThrownStone throwActions = 3;</code>
       */
      public java.util.List<com.temas.aimaster.ClientProto.ThrownStone> getThrowActionsList() {
        if (throwActionsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(throwActions_);
        } else {
          return throwActionsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.temas.aimaster.ThrownStone throwActions = 3;</code>
       */
      public int getThrowActionsCount() {
        if (throwActionsBuilder_ == null) {
          return throwActions_.size();
        } else {
          return throwActionsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.temas.aimaster.ThrownStone throwActions = 3;</code>
       */
      public com.temas.aimaster.ClientProto.ThrownStone getThrowActions(int index) {
        if (throwActionsBuilder_ == null) {
          return throwActions_.get(index);
        } else {
          return throwActionsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.temas.aimaster.ThrownStone throwActions = 3;</code>
       */
      public Builder setThrowActions(
          int index, com.temas.aimaster.ClientProto.ThrownStone value) {
        if (throwActionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureThrowActionsIsMutable();
          throwActions_.set(index, value);
          onChanged();
        } else {
          throwActionsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.temas.aimaster.ThrownStone throwActions = 3;</code>
       */
      public Builder setThrowActions(
          int index, com.temas.aimaster.ClientProto.ThrownStone.Builder builderForValue) {
        if (throwActionsBuilder_ == null) {
          ensureThrowActionsIsMutable();
          throwActions_.set(index, builderForValue.build());
          onChanged();
        } else {
          throwActionsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.temas.aimaster.ThrownStone throwActions = 3;</code>
       */
      public Builder addThrowActions(com.temas.aimaster.ClientProto.ThrownStone value) {
        if (throwActionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureThrowActionsIsMutable();
          throwActions_.add(value);
          onChanged();
        } else {
          throwActionsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.temas.aimaster.ThrownStone throwActions = 3;</code>
       */
      public Builder addThrowActions(
          int index, com.temas.aimaster.ClientProto.ThrownStone value) {
        if (throwActionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureThrowActionsIsMutable();
          throwActions_.add(index, value);
          onChanged();
        } else {
          throwActionsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.temas.aimaster.ThrownStone throwActions = 3;</code>
       */
      public Builder addThrowActions(
          com.temas.aimaster.ClientProto.ThrownStone.Builder builderForValue) {
        if (throwActionsBuilder_ == null) {
          ensureThrowActionsIsMutable();
          throwActions_.add(builderForValue.build());
          onChanged();
        } else {
          throwActionsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.temas.aimaster.ThrownStone throwActions = 3;</code>
       */
      public Builder addThrowActions(
          int index, com.temas.aimaster.ClientProto.ThrownStone.Builder builderForValue) {
        if (throwActionsBuilder_ == null) {
          ensureThrowActionsIsMutable();
          throwActions_.add(index, builderForValue.build());
          onChanged();
        } else {
          throwActionsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.temas.aimaster.ThrownStone throwActions = 3;</code>
       */
      public Builder addAllThrowActions(
          java.lang.Iterable<? extends com.temas.aimaster.ClientProto.ThrownStone> values) {
        if (throwActionsBuilder_ == null) {
          ensureThrowActionsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, throwActions_);
          onChanged();
        } else {
          throwActionsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.temas.aimaster.ThrownStone throwActions = 3;</code>
       */
      public Builder clearThrowActions() {
        if (throwActionsBuilder_ == null) {
          throwActions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          throwActionsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.temas.aimaster.ThrownStone throwActions = 3;</code>
       */
      public Builder removeThrowActions(int index) {
        if (throwActionsBuilder_ == null) {
          ensureThrowActionsIsMutable();
          throwActions_.remove(index);
          onChanged();
        } else {
          throwActionsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.temas.aimaster.ThrownStone throwActions = 3;</code>
       */
      public com.temas.aimaster.ClientProto.ThrownStone.Builder getThrowActionsBuilder(
          int index) {
        return getThrowActionsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.temas.aimaster.ThrownStone throwActions = 3;</code>
       */
      public com.temas.aimaster.ClientProto.ThrownStoneOrBuilder getThrowActionsOrBuilder(
          int index) {
        if (throwActionsBuilder_ == null) {
          return throwActions_.get(index);  } else {
          return throwActionsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.temas.aimaster.ThrownStone throwActions = 3;</code>
       */
      public java.util.List<? extends com.temas.aimaster.ClientProto.ThrownStoneOrBuilder> 
           getThrowActionsOrBuilderList() {
        if (throwActionsBuilder_ != null) {
          return throwActionsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(throwActions_);
        }
      }
      /**
       * <code>repeated .com.temas.aimaster.ThrownStone throwActions = 3;</code>
       */
      public com.temas.aimaster.ClientProto.ThrownStone.Builder addThrowActionsBuilder() {
        return getThrowActionsFieldBuilder().addBuilder(
            com.temas.aimaster.ClientProto.ThrownStone.getDefaultInstance());
      }
      /**
       * <code>repeated .com.temas.aimaster.ThrownStone throwActions = 3;</code>
       */
      public com.temas.aimaster.ClientProto.ThrownStone.Builder addThrowActionsBuilder(
          int index) {
        return getThrowActionsFieldBuilder().addBuilder(
            index, com.temas.aimaster.ClientProto.ThrownStone.getDefaultInstance());
      }
      /**
       * <code>repeated .com.temas.aimaster.ThrownStone throwActions = 3;</code>
       */
      public java.util.List<com.temas.aimaster.ClientProto.ThrownStone.Builder> 
           getThrowActionsBuilderList() {
        return getThrowActionsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.temas.aimaster.ClientProto.ThrownStone, com.temas.aimaster.ClientProto.ThrownStone.Builder, com.temas.aimaster.ClientProto.ThrownStoneOrBuilder> 
          getThrowActionsFieldBuilder() {
        if (throwActionsBuilder_ == null) {
          throwActionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.temas.aimaster.ClientProto.ThrownStone, com.temas.aimaster.ClientProto.ThrownStone.Builder, com.temas.aimaster.ClientProto.ThrownStoneOrBuilder>(
                  throwActions_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          throwActions_ = null;
        }
        return throwActionsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.temas.aimaster.ClientData)
    }

    // @@protoc_insertion_point(class_scope:com.temas.aimaster.ClientData)
    private static final com.temas.aimaster.ClientProto.ClientData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.temas.aimaster.ClientProto.ClientData();
    }

    public static com.temas.aimaster.ClientProto.ClientData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ClientData>
        PARSER = new com.google.protobuf.AbstractParser<ClientData>() {
      public ClientData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ClientData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ClientData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ClientData> getParserForType() {
      return PARSER;
    }

    public com.temas.aimaster.ClientProto.ClientData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_temas_aimaster_ThrownStone_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_temas_aimaster_ThrownStone_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_temas_aimaster_ClientData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_temas_aimaster_ClientData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021ClientProto.proto\022\022com.temas.aimaster\032" +
      "\014common.proto\"y\n\013ThrownStone\022\n\n\002id\030\001 \001(\005" +
      "\022/\n\nstartPoint\030\002 \001(\0132\033.com.temas.aimaste" +
      "r.Vector2\022-\n\010velocity\030\003 \001(\0132\033.com.temas." +
      "aimaster.Vector2\"f\n\nClientData\022\021\n\ttimeSt" +
      "amp\030\001 \001(\003\022\016\n\006packId\030\002 \001(\003\0225\n\014throwAction" +
      "s\030\003 \003(\0132\037.com.temas.aimaster.ThrownStone" +
      "P\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.temas.aimaster.Common.getDescriptor(),
        }, assigner);
    internal_static_com_temas_aimaster_ThrownStone_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_temas_aimaster_ThrownStone_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_temas_aimaster_ThrownStone_descriptor,
        new java.lang.String[] { "Id", "StartPoint", "Velocity", });
    internal_static_com_temas_aimaster_ClientData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_temas_aimaster_ClientData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_temas_aimaster_ClientData_descriptor,
        new java.lang.String[] { "TimeStamp", "PackId", "ThrowActions", });
    com.temas.aimaster.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
