// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UpdateResponse.proto

package com.temas.aimaster;

public final class UpdateResponseOuterClass {
  private UpdateResponseOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface UpdateResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.temas.aimaster.UpdateResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .com.temas.aimaster.TargetInfo target = 1;</code>
     */
    boolean hasTarget();
    /**
     * <code>optional .com.temas.aimaster.TargetInfo target = 1;</code>
     */
    com.temas.aimaster.UpdateResponseOuterClass.TargetInfo getTarget();
    /**
     * <code>optional .com.temas.aimaster.TargetInfo target = 1;</code>
     */
    com.temas.aimaster.UpdateResponseOuterClass.TargetInfoOrBuilder getTargetOrBuilder();
  }
  /**
   * Protobuf type {@code com.temas.aimaster.UpdateResponse}
   */
  public  static final class UpdateResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.temas.aimaster.UpdateResponse)
      UpdateResponseOrBuilder {
    // Use UpdateResponse.newBuilder() to construct.
    private UpdateResponse(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private UpdateResponse() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private UpdateResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.temas.aimaster.UpdateResponseOuterClass.TargetInfo.Builder subBuilder = null;
              if (target_ != null) {
                subBuilder = target_.toBuilder();
              }
              target_ = input.readMessage(com.temas.aimaster.UpdateResponseOuterClass.TargetInfo.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(target_);
                target_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.temas.aimaster.UpdateResponseOuterClass.internal_static_com_temas_aimaster_UpdateResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.temas.aimaster.UpdateResponseOuterClass.internal_static_com_temas_aimaster_UpdateResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.temas.aimaster.UpdateResponseOuterClass.UpdateResponse.class, com.temas.aimaster.UpdateResponseOuterClass.UpdateResponse.Builder.class);
    }

    public static final int TARGET_FIELD_NUMBER = 1;
    private com.temas.aimaster.UpdateResponseOuterClass.TargetInfo target_;
    /**
     * <code>optional .com.temas.aimaster.TargetInfo target = 1;</code>
     */
    public boolean hasTarget() {
      return target_ != null;
    }
    /**
     * <code>optional .com.temas.aimaster.TargetInfo target = 1;</code>
     */
    public com.temas.aimaster.UpdateResponseOuterClass.TargetInfo getTarget() {
      return target_ == null ? com.temas.aimaster.UpdateResponseOuterClass.TargetInfo.getDefaultInstance() : target_;
    }
    /**
     * <code>optional .com.temas.aimaster.TargetInfo target = 1;</code>
     */
    public com.temas.aimaster.UpdateResponseOuterClass.TargetInfoOrBuilder getTargetOrBuilder() {
      return getTarget();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (target_ != null) {
        output.writeMessage(1, getTarget());
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (target_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getTarget());
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.temas.aimaster.UpdateResponseOuterClass.UpdateResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.temas.aimaster.UpdateResponseOuterClass.UpdateResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.temas.aimaster.UpdateResponseOuterClass.UpdateResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.temas.aimaster.UpdateResponseOuterClass.UpdateResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.temas.aimaster.UpdateResponseOuterClass.UpdateResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.temas.aimaster.UpdateResponseOuterClass.UpdateResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.temas.aimaster.UpdateResponseOuterClass.UpdateResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.temas.aimaster.UpdateResponseOuterClass.UpdateResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.temas.aimaster.UpdateResponseOuterClass.UpdateResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.temas.aimaster.UpdateResponseOuterClass.UpdateResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.temas.aimaster.UpdateResponseOuterClass.UpdateResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.temas.aimaster.UpdateResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.temas.aimaster.UpdateResponse)
        com.temas.aimaster.UpdateResponseOuterClass.UpdateResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.temas.aimaster.UpdateResponseOuterClass.internal_static_com_temas_aimaster_UpdateResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.temas.aimaster.UpdateResponseOuterClass.internal_static_com_temas_aimaster_UpdateResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.temas.aimaster.UpdateResponseOuterClass.UpdateResponse.class, com.temas.aimaster.UpdateResponseOuterClass.UpdateResponse.Builder.class);
      }

      // Construct using com.temas.aimaster.UpdateResponseOuterClass.UpdateResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (targetBuilder_ == null) {
          target_ = null;
        } else {
          target_ = null;
          targetBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.temas.aimaster.UpdateResponseOuterClass.internal_static_com_temas_aimaster_UpdateResponse_descriptor;
      }

      public com.temas.aimaster.UpdateResponseOuterClass.UpdateResponse getDefaultInstanceForType() {
        return com.temas.aimaster.UpdateResponseOuterClass.UpdateResponse.getDefaultInstance();
      }

      public com.temas.aimaster.UpdateResponseOuterClass.UpdateResponse build() {
        com.temas.aimaster.UpdateResponseOuterClass.UpdateResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.temas.aimaster.UpdateResponseOuterClass.UpdateResponse buildPartial() {
        com.temas.aimaster.UpdateResponseOuterClass.UpdateResponse result = new com.temas.aimaster.UpdateResponseOuterClass.UpdateResponse(this);
        if (targetBuilder_ == null) {
          result.target_ = target_;
        } else {
          result.target_ = targetBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.temas.aimaster.UpdateResponseOuterClass.UpdateResponse) {
          return mergeFrom((com.temas.aimaster.UpdateResponseOuterClass.UpdateResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.temas.aimaster.UpdateResponseOuterClass.UpdateResponse other) {
        if (other == com.temas.aimaster.UpdateResponseOuterClass.UpdateResponse.getDefaultInstance()) return this;
        if (other.hasTarget()) {
          mergeTarget(other.getTarget());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.temas.aimaster.UpdateResponseOuterClass.UpdateResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.temas.aimaster.UpdateResponseOuterClass.UpdateResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.temas.aimaster.UpdateResponseOuterClass.TargetInfo target_ = null;
      private com.google.protobuf.SingleFieldBuilder<
          com.temas.aimaster.UpdateResponseOuterClass.TargetInfo, com.temas.aimaster.UpdateResponseOuterClass.TargetInfo.Builder, com.temas.aimaster.UpdateResponseOuterClass.TargetInfoOrBuilder> targetBuilder_;
      /**
       * <code>optional .com.temas.aimaster.TargetInfo target = 1;</code>
       */
      public boolean hasTarget() {
        return targetBuilder_ != null || target_ != null;
      }
      /**
       * <code>optional .com.temas.aimaster.TargetInfo target = 1;</code>
       */
      public com.temas.aimaster.UpdateResponseOuterClass.TargetInfo getTarget() {
        if (targetBuilder_ == null) {
          return target_ == null ? com.temas.aimaster.UpdateResponseOuterClass.TargetInfo.getDefaultInstance() : target_;
        } else {
          return targetBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.temas.aimaster.TargetInfo target = 1;</code>
       */
      public Builder setTarget(com.temas.aimaster.UpdateResponseOuterClass.TargetInfo value) {
        if (targetBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          target_ = value;
          onChanged();
        } else {
          targetBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .com.temas.aimaster.TargetInfo target = 1;</code>
       */
      public Builder setTarget(
          com.temas.aimaster.UpdateResponseOuterClass.TargetInfo.Builder builderForValue) {
        if (targetBuilder_ == null) {
          target_ = builderForValue.build();
          onChanged();
        } else {
          targetBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .com.temas.aimaster.TargetInfo target = 1;</code>
       */
      public Builder mergeTarget(com.temas.aimaster.UpdateResponseOuterClass.TargetInfo value) {
        if (targetBuilder_ == null) {
          if (target_ != null) {
            target_ =
              com.temas.aimaster.UpdateResponseOuterClass.TargetInfo.newBuilder(target_).mergeFrom(value).buildPartial();
          } else {
            target_ = value;
          }
          onChanged();
        } else {
          targetBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .com.temas.aimaster.TargetInfo target = 1;</code>
       */
      public Builder clearTarget() {
        if (targetBuilder_ == null) {
          target_ = null;
          onChanged();
        } else {
          target_ = null;
          targetBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .com.temas.aimaster.TargetInfo target = 1;</code>
       */
      public com.temas.aimaster.UpdateResponseOuterClass.TargetInfo.Builder getTargetBuilder() {
        
        onChanged();
        return getTargetFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.temas.aimaster.TargetInfo target = 1;</code>
       */
      public com.temas.aimaster.UpdateResponseOuterClass.TargetInfoOrBuilder getTargetOrBuilder() {
        if (targetBuilder_ != null) {
          return targetBuilder_.getMessageOrBuilder();
        } else {
          return target_ == null ?
              com.temas.aimaster.UpdateResponseOuterClass.TargetInfo.getDefaultInstance() : target_;
        }
      }
      /**
       * <code>optional .com.temas.aimaster.TargetInfo target = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.temas.aimaster.UpdateResponseOuterClass.TargetInfo, com.temas.aimaster.UpdateResponseOuterClass.TargetInfo.Builder, com.temas.aimaster.UpdateResponseOuterClass.TargetInfoOrBuilder> 
          getTargetFieldBuilder() {
        if (targetBuilder_ == null) {
          targetBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.temas.aimaster.UpdateResponseOuterClass.TargetInfo, com.temas.aimaster.UpdateResponseOuterClass.TargetInfo.Builder, com.temas.aimaster.UpdateResponseOuterClass.TargetInfoOrBuilder>(
                  getTarget(),
                  getParentForChildren(),
                  isClean());
          target_ = null;
        }
        return targetBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.temas.aimaster.UpdateResponse)
    }

    // @@protoc_insertion_point(class_scope:com.temas.aimaster.UpdateResponse)
    private static final com.temas.aimaster.UpdateResponseOuterClass.UpdateResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.temas.aimaster.UpdateResponseOuterClass.UpdateResponse();
    }

    public static com.temas.aimaster.UpdateResponseOuterClass.UpdateResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static final com.google.protobuf.Parser<UpdateResponse> PARSER =
        new com.google.protobuf.AbstractParser<UpdateResponse>() {
      public UpdateResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new UpdateResponse(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<UpdateResponse> getParserForType() {
      return PARSER;
    }

    public com.temas.aimaster.UpdateResponseOuterClass.UpdateResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TargetInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.temas.aimaster.TargetInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 x = 1;</code>
     */
    int getX();

    /**
     * <code>optional int32 y = 2;</code>
     */
    int getY();
  }
  /**
   * Protobuf type {@code com.temas.aimaster.TargetInfo}
   */
  public  static final class TargetInfo extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.temas.aimaster.TargetInfo)
      TargetInfoOrBuilder {
    // Use TargetInfo.newBuilder() to construct.
    private TargetInfo(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private TargetInfo() {
      x_ = 0;
      y_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private TargetInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              x_ = input.readInt32();
              break;
            }
            case 16: {

              y_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.temas.aimaster.UpdateResponseOuterClass.internal_static_com_temas_aimaster_TargetInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.temas.aimaster.UpdateResponseOuterClass.internal_static_com_temas_aimaster_TargetInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.temas.aimaster.UpdateResponseOuterClass.TargetInfo.class, com.temas.aimaster.UpdateResponseOuterClass.TargetInfo.Builder.class);
    }

    public static final int X_FIELD_NUMBER = 1;
    private int x_;
    /**
     * <code>optional int32 x = 1;</code>
     */
    public int getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 2;
    private int y_;
    /**
     * <code>optional int32 y = 2;</code>
     */
    public int getY() {
      return y_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (x_ != 0) {
        output.writeInt32(1, x_);
      }
      if (y_ != 0) {
        output.writeInt32(2, y_);
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (x_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, x_);
      }
      if (y_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, y_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.temas.aimaster.UpdateResponseOuterClass.TargetInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.temas.aimaster.UpdateResponseOuterClass.TargetInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.temas.aimaster.UpdateResponseOuterClass.TargetInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.temas.aimaster.UpdateResponseOuterClass.TargetInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.temas.aimaster.UpdateResponseOuterClass.TargetInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.temas.aimaster.UpdateResponseOuterClass.TargetInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.temas.aimaster.UpdateResponseOuterClass.TargetInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.temas.aimaster.UpdateResponseOuterClass.TargetInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.temas.aimaster.UpdateResponseOuterClass.TargetInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.temas.aimaster.UpdateResponseOuterClass.TargetInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.temas.aimaster.UpdateResponseOuterClass.TargetInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.temas.aimaster.TargetInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.temas.aimaster.TargetInfo)
        com.temas.aimaster.UpdateResponseOuterClass.TargetInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.temas.aimaster.UpdateResponseOuterClass.internal_static_com_temas_aimaster_TargetInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.temas.aimaster.UpdateResponseOuterClass.internal_static_com_temas_aimaster_TargetInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.temas.aimaster.UpdateResponseOuterClass.TargetInfo.class, com.temas.aimaster.UpdateResponseOuterClass.TargetInfo.Builder.class);
      }

      // Construct using com.temas.aimaster.UpdateResponseOuterClass.TargetInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        x_ = 0;

        y_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.temas.aimaster.UpdateResponseOuterClass.internal_static_com_temas_aimaster_TargetInfo_descriptor;
      }

      public com.temas.aimaster.UpdateResponseOuterClass.TargetInfo getDefaultInstanceForType() {
        return com.temas.aimaster.UpdateResponseOuterClass.TargetInfo.getDefaultInstance();
      }

      public com.temas.aimaster.UpdateResponseOuterClass.TargetInfo build() {
        com.temas.aimaster.UpdateResponseOuterClass.TargetInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.temas.aimaster.UpdateResponseOuterClass.TargetInfo buildPartial() {
        com.temas.aimaster.UpdateResponseOuterClass.TargetInfo result = new com.temas.aimaster.UpdateResponseOuterClass.TargetInfo(this);
        result.x_ = x_;
        result.y_ = y_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.temas.aimaster.UpdateResponseOuterClass.TargetInfo) {
          return mergeFrom((com.temas.aimaster.UpdateResponseOuterClass.TargetInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.temas.aimaster.UpdateResponseOuterClass.TargetInfo other) {
        if (other == com.temas.aimaster.UpdateResponseOuterClass.TargetInfo.getDefaultInstance()) return this;
        if (other.getX() != 0) {
          setX(other.getX());
        }
        if (other.getY() != 0) {
          setY(other.getY());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.temas.aimaster.UpdateResponseOuterClass.TargetInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.temas.aimaster.UpdateResponseOuterClass.TargetInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int x_ ;
      /**
       * <code>optional int32 x = 1;</code>
       */
      public int getX() {
        return x_;
      }
      /**
       * <code>optional int32 x = 1;</code>
       */
      public Builder setX(int value) {
        
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 x = 1;</code>
       */
      public Builder clearX() {
        
        x_ = 0;
        onChanged();
        return this;
      }

      private int y_ ;
      /**
       * <code>optional int32 y = 2;</code>
       */
      public int getY() {
        return y_;
      }
      /**
       * <code>optional int32 y = 2;</code>
       */
      public Builder setY(int value) {
        
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 y = 2;</code>
       */
      public Builder clearY() {
        
        y_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.temas.aimaster.TargetInfo)
    }

    // @@protoc_insertion_point(class_scope:com.temas.aimaster.TargetInfo)
    private static final com.temas.aimaster.UpdateResponseOuterClass.TargetInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.temas.aimaster.UpdateResponseOuterClass.TargetInfo();
    }

    public static com.temas.aimaster.UpdateResponseOuterClass.TargetInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static final com.google.protobuf.Parser<TargetInfo> PARSER =
        new com.google.protobuf.AbstractParser<TargetInfo>() {
      public TargetInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new TargetInfo(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TargetInfo> getParserForType() {
      return PARSER;
    }

    public com.temas.aimaster.UpdateResponseOuterClass.TargetInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_temas_aimaster_UpdateResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_temas_aimaster_UpdateResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_temas_aimaster_TargetInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_temas_aimaster_TargetInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024UpdateResponse.proto\022\022com.temas.aimast" +
      "er\"@\n\016UpdateResponse\022.\n\006target\030\001 \001(\0132\036.c" +
      "om.temas.aimaster.TargetInfo\"\"\n\nTargetIn" +
      "fo\022\t\n\001x\030\001 \001(\005\022\t\n\001y\030\002 \001(\005b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_temas_aimaster_UpdateResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_temas_aimaster_UpdateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_temas_aimaster_UpdateResponse_descriptor,
        new java.lang.String[] { "Target", });
    internal_static_com_temas_aimaster_TargetInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_temas_aimaster_TargetInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_temas_aimaster_TargetInfo_descriptor,
        new java.lang.String[] { "X", "Y", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
