// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UpdateRequest.proto

package com.temas.aimaster;

public final class UpdateRequestOuterClass {
  private UpdateRequestOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface UpdateRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.temas.aimaster.UpdateRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .com.temas.aimaster.UserInfo userInfo = 1;</code>
     */
    boolean hasUserInfo();
    /**
     * <code>optional .com.temas.aimaster.UserInfo userInfo = 1;</code>
     */
    com.temas.aimaster.UpdateRequestOuterClass.UserInfo getUserInfo();
    /**
     * <code>optional .com.temas.aimaster.UserInfo userInfo = 1;</code>
     */
    com.temas.aimaster.UpdateRequestOuterClass.UserInfoOrBuilder getUserInfoOrBuilder();
  }
  /**
   * Protobuf type {@code com.temas.aimaster.UpdateRequest}
   */
  public  static final class UpdateRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.temas.aimaster.UpdateRequest)
      UpdateRequestOrBuilder {
    // Use UpdateRequest.newBuilder() to construct.
    private UpdateRequest(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private UpdateRequest() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private UpdateRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.temas.aimaster.UpdateRequestOuterClass.UserInfo.Builder subBuilder = null;
              if (userInfo_ != null) {
                subBuilder = userInfo_.toBuilder();
              }
              userInfo_ = input.readMessage(com.temas.aimaster.UpdateRequestOuterClass.UserInfo.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(userInfo_);
                userInfo_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.temas.aimaster.UpdateRequestOuterClass.internal_static_com_temas_aimaster_UpdateRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.temas.aimaster.UpdateRequestOuterClass.internal_static_com_temas_aimaster_UpdateRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.temas.aimaster.UpdateRequestOuterClass.UpdateRequest.class, com.temas.aimaster.UpdateRequestOuterClass.UpdateRequest.Builder.class);
    }

    public static final int USERINFO_FIELD_NUMBER = 1;
    private com.temas.aimaster.UpdateRequestOuterClass.UserInfo userInfo_;
    /**
     * <code>optional .com.temas.aimaster.UserInfo userInfo = 1;</code>
     */
    public boolean hasUserInfo() {
      return userInfo_ != null;
    }
    /**
     * <code>optional .com.temas.aimaster.UserInfo userInfo = 1;</code>
     */
    public com.temas.aimaster.UpdateRequestOuterClass.UserInfo getUserInfo() {
      return userInfo_ == null ? com.temas.aimaster.UpdateRequestOuterClass.UserInfo.getDefaultInstance() : userInfo_;
    }
    /**
     * <code>optional .com.temas.aimaster.UserInfo userInfo = 1;</code>
     */
    public com.temas.aimaster.UpdateRequestOuterClass.UserInfoOrBuilder getUserInfoOrBuilder() {
      return getUserInfo();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (userInfo_ != null) {
        output.writeMessage(1, getUserInfo());
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (userInfo_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getUserInfo());
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.temas.aimaster.UpdateRequestOuterClass.UpdateRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.temas.aimaster.UpdateRequestOuterClass.UpdateRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.temas.aimaster.UpdateRequestOuterClass.UpdateRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.temas.aimaster.UpdateRequestOuterClass.UpdateRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.temas.aimaster.UpdateRequestOuterClass.UpdateRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.temas.aimaster.UpdateRequestOuterClass.UpdateRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.temas.aimaster.UpdateRequestOuterClass.UpdateRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.temas.aimaster.UpdateRequestOuterClass.UpdateRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.temas.aimaster.UpdateRequestOuterClass.UpdateRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.temas.aimaster.UpdateRequestOuterClass.UpdateRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.temas.aimaster.UpdateRequestOuterClass.UpdateRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.temas.aimaster.UpdateRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.temas.aimaster.UpdateRequest)
        com.temas.aimaster.UpdateRequestOuterClass.UpdateRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.temas.aimaster.UpdateRequestOuterClass.internal_static_com_temas_aimaster_UpdateRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.temas.aimaster.UpdateRequestOuterClass.internal_static_com_temas_aimaster_UpdateRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.temas.aimaster.UpdateRequestOuterClass.UpdateRequest.class, com.temas.aimaster.UpdateRequestOuterClass.UpdateRequest.Builder.class);
      }

      // Construct using com.temas.aimaster.UpdateRequestOuterClass.UpdateRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (userInfoBuilder_ == null) {
          userInfo_ = null;
        } else {
          userInfo_ = null;
          userInfoBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.temas.aimaster.UpdateRequestOuterClass.internal_static_com_temas_aimaster_UpdateRequest_descriptor;
      }

      public com.temas.aimaster.UpdateRequestOuterClass.UpdateRequest getDefaultInstanceForType() {
        return com.temas.aimaster.UpdateRequestOuterClass.UpdateRequest.getDefaultInstance();
      }

      public com.temas.aimaster.UpdateRequestOuterClass.UpdateRequest build() {
        com.temas.aimaster.UpdateRequestOuterClass.UpdateRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.temas.aimaster.UpdateRequestOuterClass.UpdateRequest buildPartial() {
        com.temas.aimaster.UpdateRequestOuterClass.UpdateRequest result = new com.temas.aimaster.UpdateRequestOuterClass.UpdateRequest(this);
        if (userInfoBuilder_ == null) {
          result.userInfo_ = userInfo_;
        } else {
          result.userInfo_ = userInfoBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.temas.aimaster.UpdateRequestOuterClass.UpdateRequest) {
          return mergeFrom((com.temas.aimaster.UpdateRequestOuterClass.UpdateRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.temas.aimaster.UpdateRequestOuterClass.UpdateRequest other) {
        if (other == com.temas.aimaster.UpdateRequestOuterClass.UpdateRequest.getDefaultInstance()) return this;
        if (other.hasUserInfo()) {
          mergeUserInfo(other.getUserInfo());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.temas.aimaster.UpdateRequestOuterClass.UpdateRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.temas.aimaster.UpdateRequestOuterClass.UpdateRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.temas.aimaster.UpdateRequestOuterClass.UserInfo userInfo_ = null;
      private com.google.protobuf.SingleFieldBuilder<
          com.temas.aimaster.UpdateRequestOuterClass.UserInfo, com.temas.aimaster.UpdateRequestOuterClass.UserInfo.Builder, com.temas.aimaster.UpdateRequestOuterClass.UserInfoOrBuilder> userInfoBuilder_;
      /**
       * <code>optional .com.temas.aimaster.UserInfo userInfo = 1;</code>
       */
      public boolean hasUserInfo() {
        return userInfoBuilder_ != null || userInfo_ != null;
      }
      /**
       * <code>optional .com.temas.aimaster.UserInfo userInfo = 1;</code>
       */
      public com.temas.aimaster.UpdateRequestOuterClass.UserInfo getUserInfo() {
        if (userInfoBuilder_ == null) {
          return userInfo_ == null ? com.temas.aimaster.UpdateRequestOuterClass.UserInfo.getDefaultInstance() : userInfo_;
        } else {
          return userInfoBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.temas.aimaster.UserInfo userInfo = 1;</code>
       */
      public Builder setUserInfo(com.temas.aimaster.UpdateRequestOuterClass.UserInfo value) {
        if (userInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          userInfo_ = value;
          onChanged();
        } else {
          userInfoBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .com.temas.aimaster.UserInfo userInfo = 1;</code>
       */
      public Builder setUserInfo(
          com.temas.aimaster.UpdateRequestOuterClass.UserInfo.Builder builderForValue) {
        if (userInfoBuilder_ == null) {
          userInfo_ = builderForValue.build();
          onChanged();
        } else {
          userInfoBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .com.temas.aimaster.UserInfo userInfo = 1;</code>
       */
      public Builder mergeUserInfo(com.temas.aimaster.UpdateRequestOuterClass.UserInfo value) {
        if (userInfoBuilder_ == null) {
          if (userInfo_ != null) {
            userInfo_ =
              com.temas.aimaster.UpdateRequestOuterClass.UserInfo.newBuilder(userInfo_).mergeFrom(value).buildPartial();
          } else {
            userInfo_ = value;
          }
          onChanged();
        } else {
          userInfoBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .com.temas.aimaster.UserInfo userInfo = 1;</code>
       */
      public Builder clearUserInfo() {
        if (userInfoBuilder_ == null) {
          userInfo_ = null;
          onChanged();
        } else {
          userInfo_ = null;
          userInfoBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .com.temas.aimaster.UserInfo userInfo = 1;</code>
       */
      public com.temas.aimaster.UpdateRequestOuterClass.UserInfo.Builder getUserInfoBuilder() {
        
        onChanged();
        return getUserInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.temas.aimaster.UserInfo userInfo = 1;</code>
       */
      public com.temas.aimaster.UpdateRequestOuterClass.UserInfoOrBuilder getUserInfoOrBuilder() {
        if (userInfoBuilder_ != null) {
          return userInfoBuilder_.getMessageOrBuilder();
        } else {
          return userInfo_ == null ?
              com.temas.aimaster.UpdateRequestOuterClass.UserInfo.getDefaultInstance() : userInfo_;
        }
      }
      /**
       * <code>optional .com.temas.aimaster.UserInfo userInfo = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.temas.aimaster.UpdateRequestOuterClass.UserInfo, com.temas.aimaster.UpdateRequestOuterClass.UserInfo.Builder, com.temas.aimaster.UpdateRequestOuterClass.UserInfoOrBuilder> 
          getUserInfoFieldBuilder() {
        if (userInfoBuilder_ == null) {
          userInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.temas.aimaster.UpdateRequestOuterClass.UserInfo, com.temas.aimaster.UpdateRequestOuterClass.UserInfo.Builder, com.temas.aimaster.UpdateRequestOuterClass.UserInfoOrBuilder>(
                  getUserInfo(),
                  getParentForChildren(),
                  isClean());
          userInfo_ = null;
        }
        return userInfoBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.temas.aimaster.UpdateRequest)
    }

    // @@protoc_insertion_point(class_scope:com.temas.aimaster.UpdateRequest)
    private static final com.temas.aimaster.UpdateRequestOuterClass.UpdateRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.temas.aimaster.UpdateRequestOuterClass.UpdateRequest();
    }

    public static com.temas.aimaster.UpdateRequestOuterClass.UpdateRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static final com.google.protobuf.Parser<UpdateRequest> PARSER =
        new com.google.protobuf.AbstractParser<UpdateRequest>() {
      public UpdateRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new UpdateRequest(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<UpdateRequest> getParserForType() {
      return PARSER;
    }

    public com.temas.aimaster.UpdateRequestOuterClass.UpdateRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UserInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.temas.aimaster.UserInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code com.temas.aimaster.UserInfo}
   */
  public  static final class UserInfo extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.temas.aimaster.UserInfo)
      UserInfoOrBuilder {
    // Use UserInfo.newBuilder() to construct.
    private UserInfo(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private UserInfo() {
      name_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private UserInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();

              name_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.temas.aimaster.UpdateRequestOuterClass.internal_static_com_temas_aimaster_UserInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.temas.aimaster.UpdateRequestOuterClass.internal_static_com_temas_aimaster_UserInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.temas.aimaster.UpdateRequestOuterClass.UserInfo.class, com.temas.aimaster.UpdateRequestOuterClass.UserInfo.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        output.writeBytes(1, getNameBytes());
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.temas.aimaster.UpdateRequestOuterClass.UserInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.temas.aimaster.UpdateRequestOuterClass.UserInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.temas.aimaster.UpdateRequestOuterClass.UserInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.temas.aimaster.UpdateRequestOuterClass.UserInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.temas.aimaster.UpdateRequestOuterClass.UserInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.temas.aimaster.UpdateRequestOuterClass.UserInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.temas.aimaster.UpdateRequestOuterClass.UserInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.temas.aimaster.UpdateRequestOuterClass.UserInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.temas.aimaster.UpdateRequestOuterClass.UserInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.temas.aimaster.UpdateRequestOuterClass.UserInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.temas.aimaster.UpdateRequestOuterClass.UserInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.temas.aimaster.UserInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.temas.aimaster.UserInfo)
        com.temas.aimaster.UpdateRequestOuterClass.UserInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.temas.aimaster.UpdateRequestOuterClass.internal_static_com_temas_aimaster_UserInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.temas.aimaster.UpdateRequestOuterClass.internal_static_com_temas_aimaster_UserInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.temas.aimaster.UpdateRequestOuterClass.UserInfo.class, com.temas.aimaster.UpdateRequestOuterClass.UserInfo.Builder.class);
      }

      // Construct using com.temas.aimaster.UpdateRequestOuterClass.UserInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.temas.aimaster.UpdateRequestOuterClass.internal_static_com_temas_aimaster_UserInfo_descriptor;
      }

      public com.temas.aimaster.UpdateRequestOuterClass.UserInfo getDefaultInstanceForType() {
        return com.temas.aimaster.UpdateRequestOuterClass.UserInfo.getDefaultInstance();
      }

      public com.temas.aimaster.UpdateRequestOuterClass.UserInfo build() {
        com.temas.aimaster.UpdateRequestOuterClass.UserInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.temas.aimaster.UpdateRequestOuterClass.UserInfo buildPartial() {
        com.temas.aimaster.UpdateRequestOuterClass.UserInfo result = new com.temas.aimaster.UpdateRequestOuterClass.UserInfo(this);
        result.name_ = name_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.temas.aimaster.UpdateRequestOuterClass.UserInfo) {
          return mergeFrom((com.temas.aimaster.UpdateRequestOuterClass.UserInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.temas.aimaster.UpdateRequestOuterClass.UserInfo other) {
        if (other == com.temas.aimaster.UpdateRequestOuterClass.UserInfo.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.temas.aimaster.UpdateRequestOuterClass.UserInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.temas.aimaster.UpdateRequestOuterClass.UserInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.temas.aimaster.UserInfo)
    }

    // @@protoc_insertion_point(class_scope:com.temas.aimaster.UserInfo)
    private static final com.temas.aimaster.UpdateRequestOuterClass.UserInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.temas.aimaster.UpdateRequestOuterClass.UserInfo();
    }

    public static com.temas.aimaster.UpdateRequestOuterClass.UserInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static final com.google.protobuf.Parser<UserInfo> PARSER =
        new com.google.protobuf.AbstractParser<UserInfo>() {
      public UserInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new UserInfo(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<UserInfo> getParserForType() {
      return PARSER;
    }

    public com.temas.aimaster.UpdateRequestOuterClass.UserInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_temas_aimaster_UpdateRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_temas_aimaster_UpdateRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_temas_aimaster_UserInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_temas_aimaster_UserInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023UpdateRequest.proto\022\022com.temas.aimaste" +
      "r\"?\n\rUpdateRequest\022.\n\010userInfo\030\001 \001(\0132\034.c" +
      "om.temas.aimaster.UserInfo\"\030\n\010UserInfo\022\014" +
      "\n\004name\030\001 \001(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_temas_aimaster_UpdateRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_temas_aimaster_UpdateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_temas_aimaster_UpdateRequest_descriptor,
        new java.lang.String[] { "UserInfo", });
    internal_static_com_temas_aimaster_UserInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_temas_aimaster_UserInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_temas_aimaster_UserInfo_descriptor,
        new java.lang.String[] { "Name", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
